### ISSUE TITLE
3 Problems in 1 + Change Rusher Shield Texture

### ISSUE THREAD

**Issue by WSDguy2014** [maikerumine/grieftest#1]
Crafting recipe for hopper is incorrect:
![screenshot_20160722_092848](https://cloud.githubusercontent.com/assets/13905392/17048589/bfd01560-4fef-11e6-969a-b3326ceaac7c.png)

Must be like this:
![screenshot_20160722_092915](https://cloud.githubusercontent.com/assets/13905392/17048606/d680390c-4fef-11e6-94be-325392210322.png)

Item frame requires owner, to break this:
![screenshot_20160722_092903](https://cloud.githubusercontent.com/assets/13905392/17048622/f9ff59a8-4fef-11e6-8c5c-c2cde43a97f5.png)

Iron trapdoor doesn't require a mesecon signal:
![screenshot_20160722_093119](https://cloud.githubusercontent.com/assets/13905392/17048648/2e21934a-4ff0-11e6-9576-896346fa74ed.png)
![screenshot_20160722_093121](https://cloud.githubusercontent.com/assets/13905392/17048653/3288659e-4ff0-11e6-976f-f38bb1f8df14.png)

You can right-click on Iron Door/Trapdoor, to open. Must be only requires to open/close the iron door/trapdoor with mesecon signal.

Rusher Shield texture looks incorrectly:
![shields_inv_shield_rusher](https://cloud.githubusercontent.com/assets/13905392/17049020/11ec0e3c-4ff3-11e6-968f-a3d2a361291a.png)

Must be OFFICIAL Rusher Shield texture like this:
![shields_inv_shield_rusher](https://cloud.githubusercontent.com/assets/13905392/17049438/07778a46-4ff6-11e6-9331-5596f814306b.png)

What looks like in Minecraft:
![image](https://cloud.githubusercontent.com/assets/13905392/17049277/fdbe1e6c-4ff4-11e6-912e-6459b6de3d3c.png)

Please. Fix the problems and change Rusher Shield texture.

**Comment by maikerumine** [comment]
Got it!  I will address these asap

**Comment by WSDguy2014** [comment]
@maikerumine All mob heads are not stackable :(    must be stackable with 64

**Comment by maikerumine** [comment]
This is intentional, all heads will be unique with meta data

**Comment by WSDguy2014** [comment]
@maikerumine Why you not added charcoal mod? charcoal mod also must be a Minecraft-like.

**Comment by WSDguy2014** [comment]
I placed on hopper, then right-clicked on hopper, it has a interface, but there's no slots. I dropped item at hopper on top, interface updates and now has a 16 slots. Must be a 5 slots instead. With side hopper, same thing.

Add a cooking recipe: Nether Brick (item)      To cook a nether brick, need a netherrack, to cook.

Change crafting recipe netherrack to nether brick, for crafting a Nether Brick Block.

Sometimes, if you destroy a netherrack, will drops nothing. Must be always drops itself.

**Comment by WSDguy2014** [comment]
Also, creeper is going to explode, blocks is not droped. Only drops from creeper. Must be spawned TNT explosion code like Rui, that made a creeper mod.

**Comment by maikerumine** [comment]
I am fixing the nether rack and cooking now, as well as looking into hopper.  The formspec might be a bit of trouble.

**Comment by WSDguy2014** [comment]
@maikerumine, i found a mesecon duplication bug on your 2b2t Minetest server. How to reproduce:

M - Mesecon
O - Any Block
-- - Nothing
L - Lever

First. Place a lever

--L------
OOOOO

Second. Place a mesecon

--L--M
OOOOO

Note: It shows on 2D, I'm not going to for screenshot.

Third. It will duplicates, break and place mesecon and repeat.

**Comment by maikerumine** [comment]
I will close these and you can open a new request for mesecons.  That is not my mod.  I updated everything today.  :)
